import { Router } from 'express';
import postRoutes from './postRoutes';
import authRoutes from './authRoutes';
import visitRoutes from './visitRoutes';
import userRoutes from './userRoutes';
import friendsRoutes from './friendsRoutes';
import commentsRoutes from './commentsRoutes';
import projectsRoutes from './projectsRoutes';
import timelineRoutes from './timelineRoutes';
import feedbackRoutes from './feedbackRoutes';
import licenseRoutes from './licenseRoutes';
import imageRoutes from './imageRoutes';
import feedRoutes from './feedRoutes';
import danmakuRoutes from './danmakuRoutes';
import configRoutes from './configRoutes';
import notificationRoutes from './notificationRoutes';
import sitemapRoutes from './sitemapRoutes';
import healthRoutes from './healthRoutes';
import pollRoutes from './pollRoutes';
import albumRoutes from './albumRoutes';
import fontRoutes from './fontRoutes';
import cardRedemptionRoutes from './cardRedemptionRoutes';
import { config } from '../config';

const router = Router();
router.use('/health', healthRoutes);
router.use('/polls', pollRoutes);
router.use('/albums', albumRoutes);
router.use('/posts', postRoutes);
router.use('/auth', authRoutes);
router.use('/visit', visitRoutes);
router.use('/user', userRoutes);
router.use('/friends', friendsRoutes);
router.use('/comments', commentsRoutes);
router.use('/projects', projectsRoutes);
router.use('/timeline', timelineRoutes);
router.use('/feedback', feedbackRoutes);
router.use('/license', licenseRoutes);
router.use('/image', imageRoutes);
router.use('/fonts', fontRoutes);
if (config.cardRedeem.enabled) router.use('/cards', cardRedemptionRoutes);
router.use('/feed', feedRoutes);
router.use('/danmaku', danmakuRoutes);
router.use('/config', configRoutes);
router.use('/notifications', notificationRoutes);
router.use('/sitemap.xml', sitemapRoutes);
router.use('/i18n', require('./i18nRoutes').default);

export default router;
